### ISSUE TITLE
Invoices submission

### ISSUE THREAD

**Issue by queply-innovations** [queply-innovations/RoyalGlassSupply-app#49]
### Submission of Invoice - incorrect and inaccurate data passed to database

`"subtotal": 0` _subtotal should be the amount of products_
`"total_tax": 0` _unknown data_
`"delivery_charge": 0` _unknown data_
`"total_amount_due": 93.5` **_data is not accurate_**

- [x] `subtotal` amount should come from invoiceItems overall price
- [x] `total_tax` don't know where to get the data of tax
- [x]  `delivery_charge` same as total_tax  or should the encoder/sales should have the right to input the delivery charge amount
- [x]  `total_amount_due` data is not accurate, still looking for solutions how to calculate overall value of amount due _**FORMULA** (total amount due = subtotal + tax + ( - discount) + delivery charge)_

**Comment by gabbyiiel** [comment]
`Total_tax` & `Delivery_charge` defaults to zero -by sir neil
