### ISSUE TITLE
Electron Printing Issues

### ISSUE THREAD

**Issue by gabbyiiel** [queply-innovations/RoyalGlassSupply-app#80]
### Current Electron Printing issues
**Issue is margin mostly? (Check image for reference)**
mura shag na center which is kalas ug space,
Ang current nga printer options sa printer for rgs is 500 dpi, both vert and horizontal, tapos ang printer options sa amo is 250 dpi.

> (left: 500dpi) almost same as rgs printer
> (right: 250dpi) almost same as rgs previous resibo _sorry pixelated android 👍_

![Image](https://github.com/queply-innovations/RoyalGlassSupply-app/assets/118502633/702050ea-661c-45fa-9f7e-2aec0cc936f6)

settings for my current setup (stash sa ako pc)

1. URL.ts
- `export const API_BASE_URL = 'https://staging.royalglasssupply.com/api';`  **set ni para di magamit ang sa production nga url**

2. main.ts

- `ipcMain.on('print-invoice', (event, data) => {`
- `pageSize: 'A4', //cut into half ang paper para tipid since mao pd ila ginagamit mostly pag gamay orders`
- `margins: { marginType: 'none' }` edit margins? di ko sure kay di mo work ang custom sa ako
- `copies: 1,`para less paper
- `dpi: { horizontal: 250, vertical: 250 },` current setup sa amo printer, **adjust lng** para ma same sa pag print

**Comment by eybrithingweird** [comment]
Added fix codes, will test print tomorrow
